In [2]:
import numpy as np
import itertools
import scipy as sp
import scipy.stats as stats

In [3]:
factor = 3
size = 140
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a1 = a[:a.size - a.size % factor]
a1.size

15

In [5]:
nan_arr = np.repeat(np.nan, factor - a.size % factor)
nan_arr

array([nan, nan])

In [41]:
a1 = np.reshape(a1, (-1, factor)).T
a1

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [42]:
a1.shape

(3, 5)

In [43]:
std = np.std(a1, axis=0)
std

array([0.81649658, 0.81649658, 0.81649658, 0.81649658, 0.81649658])

In [44]:
a1[0]

array([ 1,  4,  7, 10, 13])

In [45]:
a1[0] = np.multiply( a1[0], np.multiply(np.random.choice([-1,1], a1.shape[1]),std * size))

In [46]:
a1

array([[  114,  -457,  -800, -1143, -1486],
       [    2,     5,     8,    11,    14],
       [    3,     6,     9,    12,    15]])

In [47]:
a2 = a.copy()
a2[0:15] = a1.T.flatten()
a2

array([  114,     2,     3,  -457,     5,     6,  -800,     8,     9,
       -1143,    11,    12, -1486,    14,    15,    16])

In [35]:
t1 = np.array([True, False, False, True, True, False, False, False, True, True, True, True, False,True, False])
t1.size

15

In [36]:
for i in range(t1.size, 2, -1):
    for j in range(0, i-1):
        #print (t1[j:i])
        if np.all(t1[j:i]):
            t1[j+1:i] = np.zeros(i-j-1, dtype=bool)
t1

array([ True, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False])